In [2]:
import numpy as np
import pandas as pd
import os
import kagglehub

C:\Users\kmddg\AppData\Roaming\Python\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
path = kagglehub.dataset_download("nelgiriyewithana/global-weather-repository")
df = pd.read_csv(os.path.join(path, "GlobalWeatherRepository.csv"))

df.head()

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.12), please consider upgrading to the latest version (1.0.0).

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [4]:
print(f"{df.shape[0]:,} rows, {df.shape[1]} columns")
print(f"Cities: {df['location_name'].nunique()}  |  Countries: {df['country'].nunique()}")

dates = pd.to_datetime(df['last_updated'], errors='coerce')
print(f"Date range: {dates.min().date()} to {dates.max().date()}")

143,652 rows, 41 columns
Cities: 257  |  Countries: 211
Date range: 2024-05-16 to 2026-05-26

In [5]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,...,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,143652.000000,143652.000000,1.436520e+05,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,...,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000
mean,19.219663,21.929513,1.747819e+09,21.247633,70.247526,7.979616,12.845676,168.992927,1014.050253,29.944311,...,18.177063,448.888526,57.512747,14.796176,10.100725,23.824125,47.721258,1.685664,2.574221,49.610768
std,24.411563,65.781566,1.845421e+07,9.617896,17.312102,7.108128,11.436104,103.674296,10.165902,0.300146,...,13.663617,742.139820,30.390980,23.292985,34.709854,36.225142,147.253397,0.933338,2.421691,35.010623
min,-41.300000,-175.200000,1.715849e+09,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,27.960000,...,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,4.050300,-6.836100,1.731920e+09,15.600000,60.100000,3.800000,6.100000,80.000000,1010.000000,29.830000,...,10.200000,194.850000,38.000000,1.800000,1.110000,7.030000,9.805000,1.000000,1.000000,15.000000
50%,17.250000,23.236100,1.747817e+09,23.700000,74.600000,6.700000,10.800000,161.000000,1013.000000,29.930000,...,15.300000,286.750000,55.000000,5.735000,2.405000,13.875000,19.610000,1.000000,2.000000,49.000000
75%,40.400000,49.882200,1.763709e+09,27.900000,82.300000,11.000000,17.600000,256.000000,1018.000000,30.060000,...,24.100000,450.850000,73.000000,17.020000,8.050000,27.380000,40.854500,2.000000,3.000000,84.000000
max,64.150000,179.220000,1.779776e+09,79.300000,174.700000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,...,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000