In [2]:
import numpy as np
import pandas as pd
import os
import kagglehub

C:\Users\kmddg\AppData\Roaming\Python\Python312\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [12]:
path = kagglehub.dataset_download("nelgiriyewithana/global-weather-repository")
df = pd.read_csv(os.path.join(path, "GlobalWeatherRepository.csv"))

pd.set_option('display.max_columns', None)

df.head()

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.12), please consider upgrading to the latest version (1.0.0).

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,wind_mph,wind_kph,wind_degree,wind_direction,pressure_mb,pressure_in,precip_mm,precip_in,humidity,cloud,feels_like_celsius,feels_like_fahrenheit,visibility_km,visibility_miles,uv_index,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,8.3,13.3,338,NNW,1012.0,29.89,0.0,0.00,24,30,25.3,77.5,10.0,6.0,7.0,9.5,15.3,277.0,103.0,1.1,0.2,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,6.9,11.2,320,NW,1012.0,29.88,0.1,0.00,94,75,19.0,66.2,10.0,6.0,5.0,11.4,18.4,193.6,97.3,0.9,0.1,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,9.4,15.1,280,W,1011.0,29.85,0.0,0.00,29,0,24.6,76.4,10.0,6.0,5.0,13.9,22.3,540.7,12.2,65.1,13.4,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,7.4,11.9,215,SW,1007.0,29.75,0.3,0.01,61,100,3.8,38.9,2.0,1.0,2.0,8.5,13.7,170.2,64.4,1.6,0.2,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,8.1,13.0,150,SSE,1011.0,29.85,0.0,0.00,89,50,28.7,83.6,10.0,6.0,8.0,12.5,20.2,2964.0,19.0,72.7,31.5,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [13]:
print(f"{df.shape[0]:,} rows, {df.shape[1]} columns")
print(f"Cities: {df['location_name'].nunique()}  |  Countries: {df['country'].nunique()}")

dates = pd.to_datetime(df['last_updated'], errors='coerce')
print(f"Date range: {dates.min().date()} to {dates.max().date()}")

143,652 rows, 41 columns
Cities: 257  |  Countries: 211
Date range: 2024-05-16 to 2026-05-26

In [14]:
df.describe()

,latitude,longitude,last_updated_epoch,temperature_celsius,temperature_fahrenheit,wind_mph,wind_kph,wind_degree,pressure_mb,pressure_in,precip_mm,precip_in,humidity,cloud,feels_like_celsius,feels_like_fahrenheit,visibility_km,visibility_miles,uv_index,gust_mph,gust_kph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,moon_illumination
count,143652.000000,143652.000000,1.436520e+05,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000,143652.000000
mean,19.219663,21.929513,1.747819e+09,21.247633,70.247526,7.979616,12.845676,168.992927,1014.050253,29.944311,0.132892,0.005036,66.784437,39.772227,22.106134,71.785770,9.514074,5.621056,3.258427,11.293534,18.177063,448.888526,57.512747,14.796176,10.100725,23.824125,47.721258,1.685664,2.574221,49.610768
std,24.411563,65.781566,1.845421e+07,9.617896,17.312102,7.108128,11.436104,103.674296,10.165902,0.300146,0.560329,0.022147,23.769187,34.070492,11.518953,20.731823,2.686136,1.677398,3.532771,8.490231,13.663617,742.139820,30.390980,23.292985,34.709854,36.225142,147.253397,0.933338,2.421691,35.010623
min,-41.300000,-175.200000,1.715849e+09,-29.800000,-21.600000,2.200000,3.600000,1.000000,947.000000,27.960000,0.000000,0.000000,2.000000,0.000000,-36.700000,-34.000000,0.000000,0.000000,0.000000,2.200000,3.600000,-9999.000000,0.000000,0.000000,-9999.000000,0.168000,-1848.150000,1.000000,1.000000,0.000000
25%,4.050300,-6.836100,1.731920e+09,15.600000,60.100000,3.800000,6.100000,80.000000,1010.000000,29.830000,0.000000,0.000000,51.000000,0.000000,15.700000,60.200000,10.000000,6.000000,0.100000,6.300000,10.200000,194.850000,38.000000,1.800000,1.110000,7.030000,9.805000,1.000000,1.000000,15.000000
50%,17.250000,23.236100,1.747817e+09,23.700000,74.600000,6.700000,10.800000,161.000000,1013.000000,29.930000,0.000000,0.000000,72.000000,29.000000,25.100000,77.100000,10.000000,6.000000,1.800000,9.500000,15.300000,286.750000,55.000000,5.735000,2.405000,13.875000,19.610000,1.000000,2.000000,49.000000
75%,40.400000,49.882200,1.763709e+09,27.900000,82.300000,11.000000,17.600000,256.000000,1018.000000,30.060000,0.020000,0.000000,86.000000,75.000000,29.900000,85.800000,10.000000,6.000000,6.000000,15.000000,24.100000,450.850000,73.000000,17.020000,8.050000,27.380000,40.854500,2.000000,3.000000,84.000000
max,64.150000,179.220000,1.779776e+09,79.300000,174.700000,1841.200000,2963.200000,360.000000,3006.000000,88.770000,42.240000,1.660000,100.000000,100.000000,81.300000,178.300000,32.000000,19.000000,16.300000,1845.700000,2970.400000,38879.398000,480.700000,427.700000,521.330000,1614.100000,6037.290000,6.000000,10.000000,100.000000

In [15]:
# copy to compare original values against
df_raw = df.copy()

# Basic Assessment

## Data Cleaning & Preprocessing

In [20]:
# Checking for missing values
df.isnull().sum()

country                         0
location_name                   0
latitude                        0
longitude                       0
timezone                        0
last_updated_epoch              0
last_updated                    0
temperature_celsius             0
temperature_fahrenheit          0
condition_text                  0
wind_mph                        0
wind_kph                        0
wind_degree                     0
wind_direction                  0
pressure_mb                     0
pressure_in                     0
precip_mm                       0
precip_in                       0
humidity                        0
cloud                           0
feels_like_celsius              0
feels_like_fahrenheit           0
visibility_km                   0
visibility_miles                0
uv_index                        0
gust_mph                        0
gust_kph                        0
air_quality_Carbon_Monoxide     0
air_quality_Ozone               0
air_quality_Nitrogen_dioxide    0
air_quality_Sulphur_dioxide     0
air_quality_PM2.5               0
air_quality_PM10                0
air_quality_us-epa-index        0
air_quality_gb-defra-index      0
sunrise                         0
sunset                          0
moonrise                        0
moonset                         0
moon_phase                      0
moon_illumination               0
dtype: int64

In [21]:
# No missing values

# Checking for duplicated rows
df.duplicated().sum()

np.int64(0)

In [22]:
# Understanding the data types
df.dtypes

country                             str
location_name                       str
latitude                        float64
longitude                       float64
timezone                            str
last_updated_epoch                int64
last_updated                        str
temperature_celsius             float64
temperature_fahrenheit          float64
condition_text                      str
wind_mph                        float64
wind_kph                        float64
wind_degree                       int64
wind_direction                      str
pressure_mb                     float64
pressure_in                     float64
precip_mm                       float64
precip_in                       float64
humidity                          int64
cloud                             int64
feels_like_celsius              float64
feels_like_fahrenheit           float64
visibility_km                   float64
visibility_miles                float64
uv_index                        float64
gust_mph                        float64
gust_kph                        float64
air_quality_Carbon_Monoxide     float64
air_quality_Ozone               float64
air_quality_Nitrogen_dioxide    float64
air_quality_Sulphur_dioxide     float64
air_quality_PM2.5               float64
air_quality_PM10                float64
air_quality_us-epa-index          int64
air_quality_gb-defra-index        int64
sunrise                             str
sunset                              str
moonrise                            str
moonset                             str
moon_phase                          str
moon_illumination                 int64
dtype: object

In [23]:
# last_updated - should be time, not str
# sunrise, sunset - should be time, not str
# moonrise, moonset - should be time, not str

time_columns = [
    'last_updated',
    'sunrise',
    'sunset',
    'moonrise',
    'moonset'
]

for col in time_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')

C:\Users\kmddg\AppData\Local\Temp\ipykernel_35884\2784425753.py:14: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\kmddg\AppData\Local\Temp\ipykernel_35884\2784425753.py:14: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\kmddg\AppData\Local\Temp\ipykernel_35884\2784425753.py:14: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors='coerce')
C:\Users\kmddg\AppData\Local\Temp\ipykernel_35884\2784425753.py:14: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors='coerce')

In [24]:
# check if there were any error in conversion
df[time_columns].isna().sum()

last_updated       0
sunrise            0
sunset             0
moonrise        4876
moonset         4895
dtype: int64

In [25]:
# moonrise, moonset have problematic values - diagnose
df_raw.loc[df['moonrise'].isna(), 'moonrise'].value_counts().head(10)

moonrise
No moonrise    4838
....             16
****             13
24:00             9
Name: count, dtype: int64

In [ ]:
# 24:00 also means Moon did not rise that day, so we can replace it with NaT
# Similar for moonset

df_raw.loc[df['moonset'].isna(), 'moonset'].value_counts().head(10)

moonset
No moonset            4749
Does not set today     114
....                    16
****                    13
24:00                    3
Name: count, dtype: int64

In [27]:
df.dtypes

country                                    str
location_name                              str
latitude                               float64
longitude                              float64
timezone                                   str
last_updated_epoch                       int64
last_updated                    datetime64[us]
temperature_celsius                    float64
temperature_fahrenheit                 float64
condition_text                             str
wind_mph                               float64
wind_kph                               float64
wind_degree                              int64
wind_direction                             str
pressure_mb                            float64
pressure_in                            float64
precip_mm                              float64
precip_in                              float64
humidity                                 int64
cloud                                    int64
feels_like_celsius                     float64
feels_like_fahrenheit                  float64
visibility_km                          float64
visibility_miles                       float64
uv_index                               float64
gust_mph                               float64
gust_kph                               float64
air_quality_Carbon_Monoxide            float64
air_quality_Ozone                      float64
air_quality_Nitrogen_dioxide           float64
air_quality_Sulphur_dioxide            float64
air_quality_PM2.5                      float64
air_quality_PM10                       float64
air_quality_us-epa-index                 int64
air_quality_gb-defra-index               int64
sunrise                         datetime64[us]
sunset                          datetime64[us]
moonrise                        datetime64[us]
moonset                         datetime64[us]
moon_phase                                 str
moon_illumination                        int64
dtype: object

### Missing Values
- The dataset initially contained no standard missing values.
- During datetime conversion, some moonrise and moonset entries became NaT.
- Investigation showed these corresponded to meaningful non-time astronomical states such as "No moonrise" and "Does not set today".
- These values were intentionally preserved as NaT rather than imputed with artificial times.